//! Linux eBPF sockmap implementation using libbpf-rs.
//!
//! Loads the compiled sockmap BPF program and provides register/unregister
//! operations for socket FD pairs. Once registered, the kernel's SK_MSG
//! program redirects data directly between the paired sockets.

use std::mem;
use std::os::fd::AsFd;
use std::os::unix::io::RawFd;

use libbpf_rs::skel::{OpenSkel, SkelBuilder};
use libbpf_rs::{MapCore, OpenObject, ProgramMut};
use tracing::{debug, warn};

use crate::SockMapError;

// Generated by libbpf-cargo in build.rs
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(dead_code)]
#[allow(clippy::all)]
mod skel {
    include!(concat!(env!("OUT_DIR"), "/sockmap.skel.rs"));
}

use skel::*;

/// Must match the `struct sock_key` in sockmap.bpf.c exactly.
#[repr(C)]
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
struct SockKey {
    local_ip: u32,
    remote_ip: u32,
    local_port: u16,
    remote_port: u16,
    family: u8,
    pad: [u8; 3],
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::{Read, Write};
    use std::net::{TcpListener, TcpStream};
    use std::os::fd::AsRawFd;
    use std::sync::mpsc;
    use std::time::Duration;

    fn swapped_peer_key(key: SockKey) -> SockKey {
        SockKey {
            local_ip: key.remote_ip,
            remote_ip: key.local_ip,
            local_port: key.remote_port,
            remote_port: key.local_port,
            family: key.family,
            pad: [0; 3],
        }
    }

    #[test]
    fn swapped_tuple_does_not_identify_proxy_backend_socket() {
        let client_to_proxy = SockKey {
            local_ip: u32::from_be_bytes([127, 0, 0, 1]),
            remote_ip: u32::from_be_bytes([127, 0, 0, 1]),
            local_port: 443u16.to_be(),
            remote_port: 50_000u16.to_be(),
            family: libc::AF_INET as u8,
            pad: [0; 3],
        };
        let proxy_to_backend = SockKey {
            local_ip: u32::from_be_bytes([127, 0, 0, 1]),
            remote_ip: u32::from_be_bytes([10, 0, 0, 20]),
            local_port: 40_000u16.to_be(),
            remote_port: 8443u16.to_be(),
            family: libc::AF_INET as u8,
            pad: [0; 3],
        };

        assert_ne!(swapped_peer_key(client_to_proxy), proxy_to_backend);
    }

    #[test]
    #[ignore = "documents current sockhash value-size bug; enable when fixing eBPF"]
    fn sockhash_fd_value_size_must_match_bpf_map_value_size() {
        const BPF_SOCKHASH_VALUE_SIZE: usize = std::mem::size_of::<u64>();
        let userspace_fd_value_size = std::mem::size_of::<RawFd>();

        assert_eq!(
            userspace_fd_value_size, BPF_SOCKHASH_VALUE_SIZE,
            "userspace must write values matching the BPF sockhash map value size"
        );
    }

    #[test]
    #[ignore = "documents current IPv6 sockmap gap; enable when fixing eBPF"]
    fn ipv6_socket_key_must_not_be_encoded_as_ipv4() {
        let listener = TcpListener::bind("[::1]:0").expect("bind IPv6 listener");
        let addr = listener.local_addr().expect("listener addr");
        let (tx, rx) = mpsc::channel();

        std::thread::spawn(move || {
            let accepted = listener.accept().map(|(stream, _)| stream);
            let _ = tx.send(accepted);
        });

        let client = TcpStream::connect(addr).expect("connect IPv6 client");
        let _server = rx
            .recv()
            .expect("accept thread exited")
            .expect("accept IPv6");

        let key = sock_key_from_fd(client.as_raw_fd());
        assert!(
            match key {
                Ok(key) => key.family == libc::AF_INET6 as u8,
                Err(_) => true,
            },
            "IPv6 sockets must be encoded as AF_INET6 or explicitly rejected"
        );
    }

    fn ebpf_tests_enabled() -> bool {
        std::env::var("WICKET_EBPF_TEST").as_deref() == Ok("1")
    }

    fn connected_pair() -> std::io::Result<(TcpStream, TcpStream)> {
        let listener = TcpListener::bind("127.0.0.1:0")?;
        let addr = listener.local_addr()?;
        let (tx, rx) = mpsc::channel();

        std::thread::spawn(move || {
            let accepted = listener.accept().map(|(stream, _)| stream);
            let _ = tx.send(accepted);
        });

        let client = TcpStream::connect(addr)?;
        let server = rx.recv().expect("accept thread exited")?;
        Ok((client, server))
    }

    #[test]
    #[ignore = "requires Linux eBPF privileges; run with WICKET_EBPF_TEST=1"]
    fn ebpf_load_attach_and_register_ipv4_proxy_pair() {
        if !ebpf_tests_enabled() {
            eprintln!("skipping eBPF smoke; set WICKET_EBPF_TEST=1 to enable");
            return;
        }

        let (_client_peer, mut client_side) = connected_pair().expect("client pair");
        let (backend_side, mut backend_peer) = connected_pair().expect("backend pair");
        client_side
            .set_read_timeout(Some(Duration::from_millis(500)))
            .expect("set timeout");
        backend_peer
            .set_read_timeout(Some(Duration::from_millis(500)))
            .expect("set timeout");

        let mut sockmap = SocketMap::load(SocketMapConfig {
            bpf_object_path: None,
            max_connections: 16,
            verbose: true,
        })
        .expect("load sockmap");
        sockmap.attach().expect("attach sockmap");

        sockmap
            .register_pair(client_side.as_raw_fd(), backend_side.as_raw_fd())
            .expect("register proxy socket pair");

        backend_peer.write_all(b"probe").expect("write probe");
        let mut buf = [0; 5];
        let read = client_side.read(&mut buf).expect("read redirected bytes");
        assert_eq!(&buf[..read], b"probe");

        sockmap
            .unregister_pair(client_side.as_raw_fd(), backend_side.as_raw_fd())
            .expect("unregister proxy socket pair");
    }
}

impl SockKey {
    fn as_bytes(&self) -> &[u8] {
        unsafe {
            std::slice::from_raw_parts(self as *const Self as *const u8, mem::size_of::<Self>())
        }
    }
}

/// Extract the local and remote addresses from a socket FD into a `SockKey`.
fn sock_key_from_fd(fd: RawFd) -> Result<SockKey, SockMapError> {
    let mut local_addr: libc::sockaddr_in = unsafe { mem::zeroed() };
    let mut remote_addr: libc::sockaddr_in = unsafe { mem::zeroed() };
    let mut len = mem::size_of::<libc::sockaddr_in>() as libc::socklen_t;

    let ret = unsafe {
        libc::getsockname(
            fd,
            &mut local_addr as *mut _ as *mut libc::sockaddr,
            &mut len,
        )
    };
    if ret != 0 {
        return Err(SockMapError::Register(format!(
            "getsockname failed: {}",
            std::io::Error::last_os_error()
        )));
    }

    len = mem::size_of::<libc::sockaddr_in>() as libc::socklen_t;
    let ret = unsafe {
        libc::getpeername(
            fd,
            &mut remote_addr as *mut _ as *mut libc::sockaddr,
            &mut len,
        )
    };
    if ret != 0 {
        return Err(SockMapError::Register(format!(
            "getpeername failed: {}",
            std::io::Error::last_os_error()
        )));
    }

    Ok(SockKey {
        local_ip: local_addr.sin_addr.s_addr,
        remote_ip: remote_addr.sin_addr.s_addr,
        local_port: local_addr.sin_port,
        remote_port: remote_addr.sin_port,
        family: libc::AF_INET as u8,
        pad: [0; 3],
    })
}

/// Configuration for the eBPF sockmap.
pub struct SocketMapConfig {
    /// Path to a pre-compiled BPF object. `None` uses the embedded object.
    pub bpf_object_path: Option<String>,
    /// Maximum number of concurrent connection pairs in the sockhash map.
    pub max_connections: u32,
    /// Enable verbose BPF verifier output.
    pub verbose: bool,
}

/// eBPF sockmap for kernel-level socket redirection.
///
/// After `load()` and `attach()`, call `register_pair()` with client and
/// backend socket FDs. The kernel's SK_MSG program will then redirect data
/// directly between the two sockets without copying to userspace.
pub struct SocketMap {
    skel: SockmapSkel<'static>,
}

impl std::fmt::Debug for SocketMap {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SocketMap").finish_non_exhaustive()
    }
}

// Safety: The BPF skeleton's internal pointers reference kernel-managed
// objects that are safe to access from any thread. All call sites wrap
// SocketMap in Arc<Mutex<>>.
unsafe impl Send for SocketMap {}
unsafe impl Sync for SocketMap {}

impl SocketMap {
    /// Load the BPF program into the kernel.
    pub fn load(config: SocketMapConfig) -> Result<Self, SockMapError> {
        let mut builder = SockmapSkelBuilder::default();
        if config.verbose {
            builder.obj_builder.debug(true);
        }

        // Leak the OpenObject so the skeleton can have 'static lifetime.
        let open_object = Box::leak(Box::new(std::mem::MaybeUninit::<OpenObject>::uninit()));
        let open_skel = builder
            .open(open_object)
            .map_err(|e| SockMapError::Load(format!("open: {e}")))?;

        let skel = open_skel
            .load()
            .map_err(|e| SockMapError::Load(format!("load: {e}")))?;

        debug!(
            max_connections = config.max_connections,
            "BPF sockmap program loaded"
        );

        Ok(Self { skel })
    }

    /// Attach the SK_MSG program to the sockhash map.
    pub fn attach(&mut self) -> Result<(), SockMapError> {
        use std::os::fd::AsRawFd;

        let map_fd = self.skel.maps.sock_hash.as_fd().as_raw_fd();

        // ProgramMut doesn't have attach_sockmap directly — use the
        // Program trait method via a reference cast
        let prog: &ProgramMut<'_> = &self.skel.progs.sockmap_redir;
        prog.attach_sockmap(map_fd)
            .map_err(|e| SockMapError::Attach(format!("attach_sockmap: {e}")))?;

        debug!("SK_MSG program attached to sockhash map");
        Ok(())
    }

    /// Register a socket pair for kernel-level redirection.
    ///
    /// Both the client and backend FDs are inserted into the sockhash map
    /// with their respective 5-tuple keys. The SK_MSG program uses these
    /// entries to redirect data between the two sockets.
    pub fn register_pair(
        &mut self,
        client_fd: RawFd,
        backend_fd: RawFd,
    ) -> Result<(), SockMapError> {
        let client_key = sock_key_from_fd(client_fd)?;
        let backend_key = sock_key_from_fd(backend_fd)?;

        // Insert client socket with its key
        self.skel
            .maps
            .sock_hash
            .update(
                client_key.as_bytes(),
                &client_fd.to_ne_bytes(),
                libbpf_rs::MapFlags::ANY,
            )
            .map_err(|e| SockMapError::Register(format!("insert client: {e}")))?;

        // Insert backend socket with its key
        self.skel
            .maps
            .sock_hash
            .update(
                backend_key.as_bytes(),
                &backend_fd.to_ne_bytes(),
                libbpf_rs::MapFlags::ANY,
            )
            .map_err(|e| SockMapError::Register(format!("insert backend: {e}")))?;

        debug!(client_fd, backend_fd, "socket pair registered in sockhash");
        Ok(())
    }

    /// Unregister a socket pair, returning to userspace proxying.
    pub fn unregister_pair(
        &mut self,
        client_fd: RawFd,
        backend_fd: RawFd,
    ) -> Result<(), SockMapError> {
        let client_key = match sock_key_from_fd(client_fd) {
            Ok(k) => k,
            Err(e) => {
                warn!(client_fd, error = %e, "failed to get client key for unregister");
                return Ok(()); // Socket may already be closed
            }
        };

        let backend_key = match sock_key_from_fd(backend_fd) {
            Ok(k) => k,
            Err(e) => {
                warn!(backend_fd, error = %e, "failed to get backend key for unregister");
                return Ok(());
            }
        };

        let _ = self.skel.maps.sock_hash.delete(client_key.as_bytes());
        let _ = self.skel.maps.sock_hash.delete(backend_key.as_bytes());

        debug!(
            client_fd,
            backend_fd, "socket pair unregistered from sockhash"
        );
        Ok(())
    }
}
