//! Linux eBPF sockmap implementation using libbpf-rs.
//!
//! Loads the compiled sockmap BPF program and provides register/unregister
//! operations for socket FD pairs. Once registered, the kernel's SK_MSG
//! program redirects data directly between the paired sockets.

use std::mem;
use std::os::fd::AsFd;
use std::os::unix::io::RawFd;

use libbpf_rs::skel::{OpenSkel, SkelBuilder};
use libbpf_rs::{MapCore, OpenObject, ProgramMut};
use tracing::{debug, warn};

use crate::SockMapError;

// Generated by libbpf-cargo in build.rs
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(dead_code)]
#[allow(clippy::all)]
mod skel {
    include!(concat!(env!("OUT_DIR"), "/sockmap.skel.rs"));
}

use skel::*;

/// Must match the `struct sock_key` in sockmap.bpf.c exactly.
#[repr(C)]
#[derive(Debug, Clone, Copy, Default)]
struct SockKey {
    local_ip: u32,
    remote_ip: u32,
    local_port: u16,
    remote_port: u16,
    family: u8,
    pad: [u8; 3],
}

impl SockKey {
    fn as_bytes(&self) -> &[u8] {
        unsafe {
            std::slice::from_raw_parts(self as *const Self as *const u8, mem::size_of::<Self>())
        }
    }
}

/// Extract the local and remote addresses from a socket FD into a `SockKey`.
fn sock_key_from_fd(fd: RawFd) -> Result<SockKey, SockMapError> {
    let mut local_addr: libc::sockaddr_in = unsafe { mem::zeroed() };
    let mut remote_addr: libc::sockaddr_in = unsafe { mem::zeroed() };
    let mut len = mem::size_of::<libc::sockaddr_in>() as libc::socklen_t;

    let ret = unsafe {
        libc::getsockname(fd, &mut local_addr as *mut _ as *mut libc::sockaddr, &mut len)
    };
    if ret != 0 {
        return Err(SockMapError::Register(format!(
            "getsockname failed: {}",
            std::io::Error::last_os_error()
        )));
    }

    len = mem::size_of::<libc::sockaddr_in>() as libc::socklen_t;
    let ret = unsafe {
        libc::getpeername(fd, &mut remote_addr as *mut _ as *mut libc::sockaddr, &mut len)
    };
    if ret != 0 {
        return Err(SockMapError::Register(format!(
            "getpeername failed: {}",
            std::io::Error::last_os_error()
        )));
    }

    Ok(SockKey {
        local_ip: local_addr.sin_addr.s_addr,
        remote_ip: remote_addr.sin_addr.s_addr,
        local_port: local_addr.sin_port,
        remote_port: remote_addr.sin_port,
        family: libc::AF_INET as u8,
        pad: [0; 3],
    })
}

/// Configuration for the eBPF sockmap.
pub struct SocketMapConfig {
    /// Path to a pre-compiled BPF object. `None` uses the embedded object.
    pub bpf_object_path: Option<String>,
    /// Maximum number of concurrent connection pairs in the sockhash map.
    pub max_connections: u32,
    /// Enable verbose BPF verifier output.
    pub verbose: bool,
}

/// eBPF sockmap for kernel-level socket redirection.
///
/// After `load()` and `attach()`, call `register_pair()` with client and
/// backend socket FDs. The kernel's SK_MSG program will then redirect data
/// directly between the two sockets without copying to userspace.
pub struct SocketMap {
    skel: SockmapSkel<'static>,
}

// Safety: The BPF skeleton's internal pointers reference kernel-managed
// objects that are safe to access from any thread. All call sites wrap
// SocketMap in Arc<Mutex<>>.
unsafe impl Send for SocketMap {}
unsafe impl Sync for SocketMap {}

impl SocketMap {
    /// Load the BPF program into the kernel.
    pub fn load(config: SocketMapConfig) -> Result<Self, SockMapError> {
        let mut builder = SockmapSkelBuilder::default();
        if config.verbose {
            builder.obj_builder.debug(true);
        }

        // Leak the OpenObject so the skeleton can have 'static lifetime.
        let open_object = Box::leak(Box::new(std::mem::MaybeUninit::<OpenObject>::uninit()));
        let open_skel = builder
            .open(open_object)
            .map_err(|e| SockMapError::Load(format!("open: {e}")))?;

        let skel = open_skel
            .load()
            .map_err(|e| SockMapError::Load(format!("load: {e}")))?;

        debug!(
            max_connections = config.max_connections,
            "BPF sockmap program loaded"
        );

        Ok(Self { skel })
    }

    /// Attach the SK_MSG program to the sockhash map.
    pub fn attach(&mut self) -> Result<(), SockMapError> {
        use std::os::fd::AsRawFd;

        let map_fd = self.skel.maps.sock_hash.as_fd().as_raw_fd();

        // ProgramMut doesn't have attach_sockmap directly — use the
        // Program trait method via a reference cast
        let prog: &ProgramMut<'_> = &self.skel.progs.sockmap_redir;
        prog.attach_sockmap(map_fd)
            .map_err(|e| SockMapError::Attach(format!("attach_sockmap: {e}")))?;

        debug!("SK_MSG program attached to sockhash map");
        Ok(())
    }

    /// Register a socket pair for kernel-level redirection.
    ///
    /// Both the client and backend FDs are inserted into the sockhash map
    /// with their respective 5-tuple keys. The SK_MSG program uses these
    /// entries to redirect data between the two sockets.
    pub fn register_pair(
        &mut self,
        client_fd: RawFd,
        backend_fd: RawFd,
    ) -> Result<(), SockMapError> {
        let client_key = sock_key_from_fd(client_fd)?;
        let backend_key = sock_key_from_fd(backend_fd)?;

        // Insert client socket with its key
        self.skel
            .maps
            .sock_hash
            .update(
                client_key.as_bytes(),
                &client_fd.to_ne_bytes(),
                libbpf_rs::MapFlags::ANY,
            )
            .map_err(|e| SockMapError::Register(format!("insert client: {e}")))?;

        // Insert backend socket with its key
        self.skel
            .maps
            .sock_hash
            .update(
                backend_key.as_bytes(),
                &backend_fd.to_ne_bytes(),
                libbpf_rs::MapFlags::ANY,
            )
            .map_err(|e| SockMapError::Register(format!("insert backend: {e}")))?;

        debug!(client_fd, backend_fd, "socket pair registered in sockhash");
        Ok(())
    }

    /// Unregister a socket pair, returning to userspace proxying.
    pub fn unregister_pair(
        &mut self,
        client_fd: RawFd,
        backend_fd: RawFd,
    ) -> Result<(), SockMapError> {
        let client_key = match sock_key_from_fd(client_fd) {
            Ok(k) => k,
            Err(e) => {
                warn!(client_fd, error = %e, "failed to get client key for unregister");
                return Ok(()); // Socket may already be closed
            }
        };

        let backend_key = match sock_key_from_fd(backend_fd) {
            Ok(k) => k,
            Err(e) => {
                warn!(backend_fd, error = %e, "failed to get backend key for unregister");
                return Ok(());
            }
        };

        let _ = self.skel.maps.sock_hash.delete(client_key.as_bytes());
        let _ = self.skel.maps.sock_hash.delete(backend_key.as_bytes());

        debug!(
            client_fd,
            backend_fd, "socket pair unregistered from sockhash"
        );
        Ok(())
    }
}
